name: Build myConsoleCrasher Project

on: [push]

jobs:
  build:
    name: Build myConsoleCrasher
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build myConsoleCrasher project
      run: msbuild .\Samples\myConsoleCrasher\myConsoleCrasher.vcxproj /p:configuration=release
